### PR TITLE
Update org.yorba.shotwell.gschema.xml

### PR DESCRIPTION
**Pull request by burningTyger**
typo

### CODE REVIEW

**Comment by phako** [comment]
Hi,

the usual way to contribute to shotwell is to file an issue in GNOME bugzilla with the patch attached to the ticket (preferably using git-bz ([https://blog.fishsoup.net/2008/11/16/git-bz-bugzilla-subcommand-for-git/])

Also, your commit is lacking a proper email address and name. Can you either upate it or at least update the pull request with the missing information?

Thanks.

**Comment by burningTyger** [comment]
Unless you want me to you can just commit with your name. It's just a typo.

**Comment by phako** [comment]
Ok.

**Comment by gnomesysadmins** [comment]
Thank you for contributing to shotwell!

shotwell uses Bugzilla for code review.

If you have never contributed to GNOME before make sure you have read the
getting started documentation:
http://www.gnome.org/get-involved

Otherwise please visit
https://wiki.gnome.org/Newcomers/CodeContributionWorkflow
and follow the instructions there to upload your change to Bugzilla.

**Pull request closed without merging**
