### PR TITLE
Improve red-eye reduction algorithm

### PR DESCRIPTION
**Pull request by lauerfab**
The default red-eye reduction algorithm in shotwell usually modifies the color of every pixels in the selected area, leaving a blue/grey disk around the eye. This makes the red-eye tool not practical since it cannot be used on zoomed images. 
This modification uses a better algorithm that leaves unchanged the pixels that must not be changed, allowing the user to use a large selection area and making the tool practical even without zoom. 
The algorithm is based on the one found in GIMP.

### CODE REVIEW

**Comment by phako** [comment]
Is there already a GNOME ticket for this? I think I saw something in Bugzilla?

**Comment by lauerfab** [comment]
There is at least a copy of this github push request I wrote as a patch on Bugzilla at about the same date:  "Bug 716615 - allow red eye removal while zoomed".

**Comment by phako** [comment]
Thanks!

**Comment by gnomesysadmins** [comment]
Thank you for contributing to shotwell!

shotwell uses Bugzilla for code review.

If you have never contributed to GNOME before make sure you have read the
getting started documentation:
http://www.gnome.org/get-involved

Otherwise please visit
https://wiki.gnome.org/Newcomers/CodeContributionWorkflow
and follow the instructions there to upload your change to Bugzilla.

**Pull request closed without merging**
