### PR TITLE
Faces

### PR DESCRIPTION
**Pull request by ricardofantin**
All functions from face branch were updated with the new code.
Need to compile the program using meson with option -Dface=true.
I have started an Autotools option to compile the face options, but it doesn't work yet.

Next step will be to call opencv functions from vala code instead of c++ code.

I will try to correct any suggestion asked.

### CODE REVIEW

**Comment by phako** [comment]
I*m perfectly fine with using C++ directly.

**Comment by phako** [comment]
Please give me a bit of time, i need to familiarize with the branch myself. From a first glance, please do not commit commented code.

**Comment by ricardofantin** [comment]
Hello, Phako. I get this critical warning too. I will investigate.

**Comment by ricardofantin** [comment]
The new commit corrected the warnings shown when Photo page is show.

There are some code commented in src/faces/FacePage.vala and in ui/faces.ui . Should I remove it?

**Comment by gnomesysadmins** [comment]
Thank you for contributing to shotwell!

shotwell uses Bugzilla for code review.

If you have never contributed to GNOME before make sure you have read the
getting started documentation:
http://www.gnome.org/get-involved

Otherwise please visit
https://wiki.gnome.org/Newcomers
and follow the instructions there to upload your change to Bugzilla.

**Pull request closed without merging**
